# SPDX-FileCopyrightText: AirSonar contributors
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
  "fp-lib-table",
  "zybo_z7_i2c_breakout_v2.kicad_pcb",
  "zybo_z7_i2c_breakout_v2.kicad_pro",
  "zybo_z7_i2c_breakout_v2.kicad_sch",
  "sym-lib-table",
]
SPDX-FileCopyrightText = "AirSonar contributors"
SPDX-License-Identifier = "CERN-OHL-W-2.0"
